### ISSUE TITLE
Unexpected ")" in style.user.css on line 400

### ISSUE THREAD

**Issue by Teraskull** [STaRDoGG/portainer-nord-dark-theme#15]
https://github.com/STaRDoGG/portainer-nord-dark-theme/blob/2059012bc64316fe62359036ed13b13a67c35cd5/style.user.css#L400

![image](https://user-images.githubusercontent.com/24798198/147048980-15bd5cc0-dfba-42f4-9829-bba0259de34d.png)

**Comment by jscottelblein** [comment]
@Teraskull Sorry bro, just now seeing this. remove the `)` just before the comma.

I'll hopefully be releasing another update soon, time permitting.
