### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by seevee** [STaRDoGG/portainer-nord-dark-theme#2]
At the time of this issue, the license of this project is AGPL.

I'm not a lawyer, but GPL is copyleft. I'm fairly certain that if portainer were to use this code, they'd have to distribute portainer under AGPL, which they're not doing.

Maybe since the end goal is to get this rolled in, use the same license that they're using ([zlib](https://github.com/portainer/portainer/blob/develop/LICENSE))?

**Comment by jscottelblein** [comment]
@seevee I'll check it out. I'm not real familiar with all of these licenses and just spun the dial when choosing one.
